runtime: python37

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  CLOUD_SQL_CONNECTION_NAME: my-web-271300:asia-east2:myweb-mysql
  DB_USER: root
  DB_PASS: 52duckli1314
  DB_NAME: my_web